### ISSUE TITLE
Hello, I have a question

### ISSUE THREAD

**Issue by DaXiong1949** [aniqfakhrul/Certifried#1]
CRITICAL:root:SAMR SessionError: code: 0xc00002a7 - STATUS_DS_NO_RIDS_ALLOCATED - The directory service was unable to allocate a relative identifier.
ERROR:root:'NoneType' object has no attribute 'startswith'

**Comment by aniqfakhrul** [comment]
Not really sure what happens in background but does it create a computer account?

**Comment by DaXiong1949** [comment]
Just checked, no account was created
